### ISSUE TITLE
Post open source release

### ISSUE THREAD

**Issue by marcusmolchany** [Fullscreen/filterjitsu#15]
The following items should be completed immediately [post open source release](https://github.com/Fullscreen/filterjitsu/issues/7)

- [x] integrate with travis-ci
- [x] host on CDN
- [x] create github pages with documentation and examples

**Comment by claudiofullscreen** [comment]
It's public!!!

![open source](http://www.dototot.com/wp-content/uploads/2015/03/shebang2.gif)

**Comment by marcusmolchany** [comment]
😁

**Comment by marcusmolchany** [comment]
https://github.com/jsdelivr/jsdelivr/pull/12852

PR to add filterjitsu to jsdelivr

**Comment by marcusmolchany** [comment]
https://github.com/jsdelivr/jsdelivr/pull/12852

**Comment by marcusmolchany** [comment]
https://fullscreen.github.io/filterjitsu/

i think just updating the `index.html` file we have is the easiest way to do github pages for this project. no extra work

**Comment by marcusmolchany** [comment]
closing this one
