### ISSUE TITLE
"Clear search query params" link is not correct

### ISSUE THREAD

**Issue by marcusmolchany** [Fullscreen/filterjitsu#23]
https://github.com/Fullscreen/filterjitsu/blob/master/index.html#L17

this works if the top level domain is using filterjitsu but if it exists on any nested url it takes you back to the root domain.

**Comment by marcusmolchany** [comment]
for example on the example page https://fullscreen.github.io/filterjitsu/

**Comment by bruce-fs** [comment]
@marcusmolchany - just to make sure I understand the implication, are you saying filterjitsu should have awareness (however that is achieved) of whatever "nested directory" the browser is pointed at as the plugin is working its filtering magic?  For example, if a user navigates to a page such as localhost:3000/filterjitsu/nested and then fires a filter such that you have localhost:3000/filterjitsu/nested?category=official&type=YouTube then filterjitsu would consider "localhost:3000/filterjitsu/nested" to be the "top level url" to be the state to reset to when you clear search query params?  So when a user clicks "clear search query params" in index.html#L17, the browser url bar should read "localhost:3000/filterjitsu/nested" as opposed to "localhost:3000"?  

The way it's behaving now when a user clicks 

```HTML
 <li><a href="/">Clear search query params</a></li>
```

I would expect it to go to the root directory which is localhost:3000 in development and  https://fullscreen.github.io/ in production.

Here's a PR w/a simple fix: https://github.com/Fullscreen/filterjitsu/pull/25 (tested on Chrome)

**Comment by claudiofullscreen** [comment]
@bruce-fs I think the problem here is only **specific to the example**.

To clear the filters, you would just return to whatever page you are on.

**Comment by marcusmolchany** [comment]
Missed the discussion here but https://github.com/Fullscreen/filterjitsu/pull/25 solves this.

The issue appeared if we had a domain, for instance fullscreen.com, and had an application using filterjitsu on a nested route. Previously if the user was on fullscreen.com/filterjitsu?type=Video and tried to clear the parameters (as per the a tag in our documentation) they would end up on fullscreen.com. Instead we want them to stay on the nested route where filterjitsu was initialized.
